# 示例自定义任务配置
task_id: "example_custom_task"
name: "示例自定义任务"
description: "这是一个示例自定义任务，用于演示系统功能"
type: "custom"
enabled: true
priority: 4

# 调度配置
schedule:
  type: "cron"
  cron_expressions:
    - "50 17 * * *"

# 自定义任务配置
custom:
  # 任务目标配置
  task_objective:
    description: "如何把AI集成到我的工作中，提升效率，并给出具体方案"
    input_sources:

    # 任务复杂度
    complexity: "low"  # low, medium, high
    estimated_duration: "5分钟"
    
    # 具体目标
    goals:
      - "给出简要方案"
  
  # 输出要求
  output_requirements:
    format: "markdown"  # 支持 markdown, excel, ppt
    include_charts: false
    include_recommendations: false
    include_priority_ranking: false
    include_action_items: false

# AI配置
ai:
  primary_model: "deepseek"
  fallback_model: "claude"
  custom_prompt: "这是一个自定义任务"

# 输出配置
output:
  format: "markdown"
  output_path: "./outputs/custom_tasks"
  filename_template: "code_quality_report_{timestamp}"
  
  # 多格式输出支持
  multi_format:
    markdown: true
    excel: false
    ppt: false
  
  # 输出内容结构
  content_structure:
    executive_summary: true
    detailed_analysis: true
    charts_and_graphs: true
    recommendations: true
    action_plan: true

# 重试配置
retry:
  max_attempts: 3
  base_delay: 120
  max_delay: 1800
  backoff_multiplier: 2
  jitter: 0.1

# 超时配置
timeout:
  task_timeout: 1800  # 30分钟
  ai_timeout: 900     # 15分钟
  data_processing_timeout: 300  # 5分钟

# 通知配置
notify:
  on_start: true
  on_complete: true
  on_error: true
  at_users: ["@技术负责人", "@质量工程师"]
  
  # 特殊通知条件
  special_notifications:
    critical_issues: true      # 发现关键问题时通知
    quality_score_below: 70   # 质量分数低于70时通知
    high_priority_issues: 3   # 高优先级问题超过3个时通知

# 任务依赖配置
dependencies:
  required_tasks: []  # 依赖的其他任务
  required_files:     # 依赖的文件
    - "./example_project"
    - "./metrics/code_quality.json"
  
# 执行策略
execution_strategy:
  parallel_processing: false  # 是否支持并行处理
  resource_requirements:      # 资源需求
    memory: "512MB"
    cpu: "1 core"
  priority_level: "normal"    # 执行优先级
