# AI模型管理任务示例配置
task_id: "ai_model_management_example"
name: "AI模型管理示例"
description: "演示AI模型管理功能的示例任务"
type: "ai_model_management"
enabled: true
priority: 5

# 调度配置
schedule:
  type: "manual"

# AI模型管理配置
ai_model_management:
  operation: "register_model"  # 操作类型: register_model, set_active_model, list_models, update_performance, get_statistics, export_model, import_model, delete_model
  
  # 模型配置（用于register_model和import_model操作）
  model_config:
    model_name: "claude-3-sonnet"
    model_type: "text_generation"
    version: "20240229"
    provider: "anthropic"
    api_key: "${ANTHROPIC_API_KEY}"
    endpoint: "https://api.anthropic.com"
    parameters:
      max_tokens: 4000
      temperature: 0.7
    set_active: true  # 注册后是否设置为活跃模型
  
  # 版本ID（用于set_active_model, export_model, delete_model操作）
  # version_id: "abc123def456"
  
  # 性能数据（用于update_performance操作）
  # performance_data:
  #   version_id: "abc123def456"
  #   response_time: 2.5
  #   success: true
  #   cost: 0.05
  #   tokens_used: 1500
  #   error_message: null
  
  # 过滤条件（用于list_models操作）
  # model_type: "text_generation"
  # status: "active"

# 输出配置
output:
  output_path: "./outputs/ai_model_management"
  filename_template: "ai_model_management_{operation}_{timestamp}"

# 重试配置
retry:
  max_attempts: 2
  base_delay: 30
  max_delay: 300
  backoff_multiplier: 2
  jitter: 0.1

# 超时配置
timeout:
  task_timeout: 600   # 10分钟
  operation_timeout: 300  # 5分钟

# 通知配置
notify:
  on_start: true
  on_complete: true
  on_error: true
  channels: ["console"]
