# 增强的全局配置文件示例
name: "AutoCoder AI Task Framework"
version: "2.0.0"
max_concurrent_tasks: 10

# AI服务配置
ai_services:
  default: "openai"
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    max_tokens: 4000
    temperature: 0.7
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "claude-3-sonnet"
    max_tokens: 4000
  google:
    api_key: "${GOOGLE_API_KEY}"
    model: "gemini-pro"
  azure:
    api_key: "${AZURE_API_KEY}"
    endpoint: "https://your-resource.openai.azure.com/"
    model: "gpt-4"
    api_version: "2024-02-15-preview"

# Git配置
git:
  default: "github"
  github:
    token: "${GITHUB_TOKEN}"
    username: "your-username"
    base_url: "https://api.github.com"
  gitlab:
    token: "${GITLAB_TOKEN}"
    username: "your-username"
    base_url: "https://gitlab.com/api/v4"

# 通知配置
notifications:
  channels:
    email:
      type: "smtp"
      host: "smtp.gmail.com"
      port: 587
      username: "${EMAIL_USERNAME}"
      password: "${EMAIL_PASSWORD}"
      from_address: "noreply@yourcompany.com"
      to_addresses: ["admin@yourcompany.com"]
    slack:
      type: "webhook"
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#ai-tasks"
    webhook:
      type: "http"
      url: "${WEBHOOK_URL}"
      method: "POST"
      headers:
        Authorization: "Bearer ${WEBHOOK_TOKEN}"

# 编码规范配置
coding_standards:
  python:
    file_path: "standards/python_coding_standards.md"
    linter: "pylint"
    formatter: "black"
  java:
    file_path: "standards/java_coding_standards.md"
    linter: "checkstyle"
    formatter: "google-java-format"
  javascript:
    file_path: "standards/javascript_coding_standards.md"
    linter: "eslint"
    formatter: "prettier"

# 安全配置
security:
  encryption:
    algorithm: "AES"
    key_size: 256
    key_file: "config/encryption.key"
  access_control:
    ip_whitelist:
      - "192.168.1.0/24"
      - "10.0.0.0/8"
    authentication:
      type: "jwt"
      secret: "${JWT_SECRET}"
      expires_in: 3600
  audit:
    enabled: true
    log_file: "logs/audit.log"
    retention_days: 90

# 性能配置
performance:
  cache:
    type: "redis"
    host: "localhost"
    port: 6379
    max_size: 1000
    ttl: 3600
  connection_pool:
    max_connections: 20
    min_connections: 5
    connection_timeout: 30
    idle_timeout: 300
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20

# 监控配置
monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"
    port: 9090
  health_check:
    enabled: true
    endpoint: "/health"
    interval: 30
  logging:
    level: "INFO"
    format: "json"
    file: "logs/application.log"
    max_size: "100MB"
    backup_count: 5

# 任务模板配置
task_templates:
  coding:
    default_ai_provider: "openai"
    default_model: "gpt-4"
    max_file_size: 1048576  # 1MB
    supported_languages:
      - "python"
      - "java"
      - "javascript"
      - "typescript"
      - "go"
      - "rust"
  review:
    review_criteria:
      - "code_quality"
      - "security"
      - "performance"
      - "maintainability"
    auto_approve_threshold: 0.8
  doc:
    output_formats:
      - "markdown"
      - "html"
      - "pdf"
    template_path: "templates/doc_templates/"

# 错误处理配置
error_handling:
  retry_policy:
    max_attempts: 3
    backoff_factor: 2
    max_delay: 300
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3
  fallback:
    enabled: true
    default_response: "服务暂时不可用，请稍后重试"

# 国际化配置
internationalization:
  default_locale: "zh_CN"
  supported_locales:
    - "zh_CN"
    - "en_US"
    - "ja_JP"
  message_files:
    zh_CN: "i18n/zh_CN.json"
    en_US: "i18n/en_US.json"
    ja_JP: "i18n/ja_JP.json"
