# 智能任务生成任务示例配置
task_id: "intelligent_task_example"
name: "智能任务生成示例"
description: "使用自然语言描述生成任务配置的示例任务"
type: "intelligent_task"
enabled: true
priority: 5

# 调度配置
schedule:
  type: "manual"

# 智能任务生成配置
intelligent_task:
  description: "请为我生成一个用户管理系统的API文档生成任务，包括用户注册、登录、信息修改等功能，要求生成详细的接口文档，包含请求参数、响应格式和错误码说明"
  context:
    project_type: "web_application"
    technology_stack: "Spring Boot + MySQL"
    target_audience: "前端开发人员"
    documentation_style: "RESTful API"

# AI配置
ai:
  primary_model: "claude"
  model: "claude-3-sonnet-20240229"
  max_tokens: 6000
  temperature: 0.1

# 输出配置
output:
  format: "multiple"
  output_path: "./outputs/intelligent_tasks"
  filename_template: "generated_task_{timestamp}"
  
  # 多格式输出支持
  multi_format:
    json: true
    yaml: true
    markdown: true

# 重试配置
retry:
  max_attempts: 2
  base_delay: 30
  max_delay: 300
  backoff_multiplier: 2
  jitter: 0.1

# 超时配置
timeout:
  task_timeout: 1800   # 30分钟
  ai_timeout: 1200     # 20分钟

# 通知配置
notify:
  on_start: true
  on_complete: true
  on_error: true
  channels: ["console"]
