# 编码任务示例配置
task_id: "auto-webhook-tool"
name: "auto-webhook-tool"
description: "webhook回调工具"
type: "coding"
enabled: false

# 工作流配置
workflow_mode: "automated"  # manual 或 automated

# 任务调度配置
schedule:
  type: "cron"
  cron_expressions: ["28 15 * * *"]  # 18点20分执行（用于测试）
  timezone: "UTC+8"

# 编码任务特定配置
coding:
  base_branch: "master"
  branch_name: "feature/webhook-tool"
  project_path: "outputs/auto-webhook-tool"
  repo_url: "https://github.com/ad19900913/auto-webhook-tool"
  prompt: "使用最新的前端框架和UI框架实现一套webhook回调地址、回调消息管理工具，包括webhook地址的增删改查、webhook回调消息的查询功能"