# 编码任务示例配置
task_id: "coding_task_example"
name: "编码任务示例"
description: "使用工作流引擎执行的编码任务示例"
type: "coding"
enabled: true

# 工作流配置
workflow_mode: "manual"  # manual 或 automated

# 任务调度配置
schedule:
  type: "cron"
  expression: "0 9 * * 1-5"  # 工作日早上9点执行
  timezone: "UTC+0"

# 任务参数
parameters:
  description: "开发一个简单的用户管理模块，包括用户注册、登录、信息修改功能"
  repo_url: "https://github.com/example/user-management"
  branch: "main"
  output_dir: "outputs/coding_tasks"

# AI配置
ai:
  provider: "claude"
  model: "claude-3-sonnet-20240229"
  temperature: 0.7
  max_tokens: 4000

# Git配置
git:
  platform: "github"
  token: "${GITHUB_TOKEN}"
  username: "auto-coder"
  email: "auto-coder@example.com"

# 通知配置
notifications:
  channels:
    - "dingtalk"
  events:
    - "task_start"
    - "task_complete"
    - "task_error"
    - "human_approval_required"

# 重试配置
retry:
  max_attempts: 3
  backoff_factor: 2
  max_delay: 3600

# 超时配置
timeout:
  task: 7200  # 2小时
  step: 1800  # 30分钟

# 工作流特定配置
workflow_config:
  shortcuts_enabled: true
  dod_check_enabled: true
  artifact_retention_days: 30
