# 文档生成任务示例配置
task_id: "doc_task_example"
name: "文档生成任务示例"
description: "使用工作流引擎执行的文档生成任务示例"
type: "doc"
enabled: true

# 工作流配置
workflow_mode: "manual"  # manual 或 automated

# 任务调度配置
schedule:
  type: "cron"
  expression: "0 10 * * 1"  # 每周一早上10点执行
  timezone: "UTC+0"

# 任务参数
parameters:
  description: "生成用户管理模块的API文档"
  document_type: "API文档"
  project_info: "用户管理系统"
  repo_url: "https://github.com/example/user-management"
  branch: "main"
  target_audience: "开发人员"
  output_dir: "outputs/doc_tasks"

# AI配置
ai:
  provider: "claude"
  model: "claude-3-sonnet-20240229"
  temperature: 0.5
  max_tokens: 6000

# Git配置
git:
  platform: "github"
  token: "${GITHUB_TOKEN}"
  username: "doc-generator"
  email: "docs@example.com"

# 通知配置
notifications:
  channels:
    - "dingtalk"
  events:
    - "task_start"
    - "task_complete"
    - "task_error"
    - "human_approval_required"

# 重试配置
retry:
  max_attempts: 2
  backoff_factor: 2
  max_delay: 1800

# 超时配置
timeout:
  task: 5400  # 1.5小时
  step: 1200  # 20分钟

# 工作流特定配置
workflow_config:
  shortcuts_enabled: true
  dod_check_enabled: true
  artifact_retention_days: 90
  output_formats:
    - "markdown"
    - "html"
  include_diagrams: true
  include_examples: true
