# Gemini AI任务示例配置
task_id: "gemini-web-app"
name: "Gemini编码示例"
description: "使用Gemini AI服务生成一个现代化的Web应用"
type: "coding"
enabled: true

# 工作流配置
workflow_mode: "automated"  # manual 或 automated

# 任务调度配置
schedule:
  type: "cron"
  cron_expressions: ["46 08 * * *"]  # 每天10点执行
  timezone: "UTC+8"

# 编码任务特定配置
coding:
  base_branch: "master"
  branch_name: "feature/gemini-web-app"
  project_path: "outputs/gemini-web-app"
  repo_url: "https://github.com/ad19900913/gemini-web-app"
  prompt: "使用React和TypeScript创建一个现代化的待办事项应用，包含以下功能：1. 添加、删除、编辑待办事项 2. 标记完成/未完成状态 3. 按优先级排序 4. 搜索和过滤功能 5. 响应式设计 6. 本地存储支持"